version: '3'

services:
  grafana:
    image: grafana/grafana-oss:latest
    user: 1000
    container_name: grafana
    environment:
      - GF_USERS_ALLOW_SIGN_UP=false
      - GF_PATHS_CONFIG=/etc/grafana/grafana.ini
      - GF_PATHS_DATA=/var/lib/grafana
      - GF_PATHS_HOME=/usr/share/grafana
      - GF_PATHS_LOGS=/var/log/grafana
      - GF_PATHS_PLUGINS=/var/lib/grafana/plugins
      - GF_PATHS_PROVISIONING=/etc/grafana/provisioning 
    ports:
      - "3000:3000"
    volumes:
      - ./grafana:/var/lib/grafana
      - ./grafana/grafana.ini:/etc/grafana/grafana.ini
      - ./grafana/provisioning:/etc/grafana/provisioning
    restart: unless-stopped

  prometheus:
    image: prom/prometheus:latest
    container_name: prometheus
    user: 1000
    ports:
      - "9090:9090"
    volumes:
      - ./prometheus/config:/etc/prometheus
      - ./prometheus/:/prometheus
    restart: unless-stopped
    command:
      - '--config.file=/etc/prometheus/prometheus.yml'
      - '--storage.tsdb.path=/prometheus'
    links:
      #      - cadvisor:cadvisor
      - node-exporter:node-exporter

        #  cadvisor:
        #    image: zcube/cadvisor:latest
        #    container_name: cadvisor
        #    ports:
        #      - "8080:8080"
        #    ipc: shareable
        #    privileged: true
        #    volumes:
        #      - /:/rootfs:ro
        #      - /var/run:/var/run:ro
        #      - /sys:/sys:ro
        #      - /var/lib/docker/:/var/lib/docker:ro
        #      - /dev/disk/:/dev/disk:ro
        #      - /var/lib/containers/:/var/lib/containers:ro
        #      - /run/podman/podman.sock:/run/podman/podman.sock:rw
        #      - /etc/machine-id:/etc/machine-id:ro
        #    devices:
        #      - /dev/kmsg:/dev/kmsg
        #    restart: unless-stopped
        #    security_opt:
        #      - label=disable

  node_exporter:
    image: quay.io/prometheus/node-exporter:latest
    container_name: node-exporter
    ports:
      - "9100:9100"
    command:
      - '--path.rootfs=/host'
    pid: host
    restart: unless-stopped
    volumes:
      - '/:/host:ro,rslave'

  loki:
    image: grafana/loki:latest
    container_name: loki
    ports:
      - "3100:3100"
    command: -config.file=/etc/loki/local-config.yaml

  promtail:
    image: grafana/promtail:latest
    container_name: promtail
    volumes:
      - /tmp/:/tmp/
      - /var/log:/var/log
      - ./promtail/config/config.yml:/etc/promtail/config.yml
    command: -config.file=/etc/promtail/config.yml

