scrape_configs:
  - job_name: 'pi'
    scrape_interval: 15s
    static_configs:
      - targets: ['localhost:9090', '192.168.1.92:8080', 'node-exporter:9100']

  - job_name: 'burealis'
    scrape_interval: 15s
    static_configs:
      - targets: ['192.168.1.69:9100']

  - job_name: 'nodes'
    scrape_interval: 15s
    static_configs:
      - targets: ['10.89.0.1:9100', '10.89.0.2:9100', '10.89.0.3:9100']
